//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedBuildings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedBuildings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY is an international fashion brand that has represented style and quality since DATE. COMPANY works on a basis of creativity and responsibility fused with a sunny Californian attitude. Effortless style, authenticity and easy-going living are at the heart of the brand philosophy. These positive values shine through at every level, from the laid-back tailoring and hand-crafted details to the made-to-last quality, use of natural materials and responsible production. International designers bring the bra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsCommercial {
            get {
                return ResourceManager.GetString("descriptionsCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in SITY, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///Started in DATE, COMPANY is a power management company with 2014 sale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsFarm {
            get {
                return ResourceManager.GetString("descriptionsFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in SITY, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///Started in DATE, COMPANY is a power management company with 2014 sale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsForest {
            get {
                return ResourceManager.GetString("descriptionsForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in SITY, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///Started in DATE, COMPANY is a power management company with 2014 sale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsIndustrial {
            get {
                return ResourceManager.GetString("descriptionsIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in SITY, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///Started in DATE, COMPANY is a power management company with 2014 sale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsMine {
            get {
                return ResourceManager.GetString("descriptionsMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY is a global management consulting firm that serves leading businesses, governments, non governmental organizations, and not-for-profits. We help our clients make lasting improvements to their performance and realize their most important goals. Over nearly a century, we’ve built a firm uniquely equipped to this task.
        ///COMPANY is SITY&apos;s leading communications group. We provide a diverse range of services including fixed, mobile, data, internet, TV and infocomms technology (ICT) as well as digital solu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsOffices {
            get {
                return ResourceManager.GetString("descriptionsOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in SITY, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///Started in DATE, COMPANY is a power management company with 2014 sale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsOil {
            get {
                return ResourceManager.GetString("descriptionsOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY offers serviced apartments characterized by touches of indulgence that spells of sophistication and timeless classics, with rich textures and distinctive décor that reflect the essence of the host city.  Be it Dubai, UK or any of the key gateway cities we are in, every property offers corporate housing apartments with highly desirable addresses in key business and prestigious districts where city charm reigns in the metropolis. 
        ///At COMPANY, elite meets exquisite, class meets convenience. In one dar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsResidential {
            get {
                return ResourceManager.GetString("descriptionsResidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaime&apos;s Trusty Animal Store
        ///Flannery&apos;s Fine Antique Shoppe
        ///The Fancy Book Shop
        ///Uncle Barry&apos;s Quality Bridal Wear Marketplace
        ///Topless Himalayan Wine Boutique
        ///Jett&apos;s Dope Clothing Department Store
        ///Pretty Brilliant Asian Center
        ///Leandro&apos;s Awesome Umbrella Enterprise
        ///Bobo&apos;s Seedy Mattress Warehouse
        ///Cheap and Baller Educational Skeleton Thrift Shop
        ///Chippy&apos;s Marvelous Video Games
        ///Pepper&apos;s Worthy Recycled Food Cafe
        ///Pico&apos;s Freaky Fish Stick Restaurant
        ///Lind Entertainement
        ///Andrews Fashion Center
        ///Bilyk Galleria
        ///Boutiqu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nameCommercial {
            get {
                return ResourceManager.GetString("nameCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Acres
        ///The Happy Strawberry
        ///The Pruners
        ///Vines of Love
        ///Hydroponic Futures
        ///Peas and Carrots Farm
        ///Soilent Green
        ///The Compost Heap
        ///Shade-Grown Coffee Company
        ///Cheese Factory
        ///Laughing Goat Cheeses
        ///Flew The Coop Chicken Farm
        ///The Dude Ranch
        ///Alpacas For Less
        ///The Lowing Cow
        ///Sheepish Dreams
        ///Love and Corn
        ///Cheery Rows.
        /// </summary>
        public static string nameFarm {
            get {
                return ResourceManager.GetString("nameFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muir Woods
        ///Redwood Glen
        ///Country Falls
        ///Beauty Woods
        ///Pine Grove
        ///Cedar Dreams
        ///Yellowpebble Park
        ///Hundred Acres.
        /// </summary>
        public static string nameForest {
            get {
                return ResourceManager.GetString("nameForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceritfied Earth Movers Inc.
        ///Barkley&apos;s Gold Digger Industries
        ///Ballarat Bedrock Mines Corproration 
        ///The Boulder Quarry Syndicate
        ///Family Gravel Business Enterprise
        ///Doug&apos;s Titanium Miner Union
        ///Grandma&apos;s Aluminium Deposit Association
        ///Eureka Silver Reserves Multinational
        ///Klondike&apos;s Copper Trade Company
        ///Plinkett&apos;s Chromium Collector Organisation
        ///Walter&apos;s Platinum Merchant Congolomorate
        ///Californian Uranium Holdings League
        ///Crystal&apos;s Iron Fist Alliance
        ///Heavy Metal Industries
        ///Blue Steel Mill
        ///Rock and Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nameIndustrial {
            get {
                return ResourceManager.GetString("nameIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douglas Iron Works
        ///Stone and Steel
        ///Aggregate Inc.
        ///Graniteworks LLC
        ///Stone and Time
        ///Sedimentary Dreams
        ///Copper and Steel Pits
        ///Quench Inc..
        /// </summary>
        public static string nameMine {
            get {
                return ResourceManager.GetString("nameMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceritfied Inc.
        ///Ballarat Bedrock Corproration 
        ///Flipper&apos;s Quaint Online Law Firm
        ///The Multinational Accounting Enterprise
        ///Lightning Fast Efficient Rope Company
        ///Fickle Heart Marvelous Simulation Games
        ///Remarkably Pleasant Travel Alliance
        ///Atilla&apos;s Competent Adventure Corporation
        ///Sid&apos;s Digital Mobile Conglomerate
        ///Peacock and Co. Licensed Telecommunications Business
        ///Lincoln&apos;s Skilled Cooking Solutions
        ///Frankie&apos;s Professional Mind Control Services
        ///Cheap and Frenzied Security League
        ///Ace&apos;s Slick Board Orga [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nameOffices {
            get {
                return ResourceManager.GetString("nameOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nameOil {
            get {
                return ResourceManager.GetString("nameOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rookery Building
        ///Boleyn Tower 
        ///Bennett Houses
        ///Patterson Houses
        ///One Hagley Road
        ///Celestia Tower
        ///La Guardia Apartments
        ///Liberte
        ///Tung Chung Crescent
        ///Fraiser Suites
        ///Belvedere Luxury Apartments
        ///Kollmann Apartments
        ///Burbank Apartments
        ///The Mansands
        ///The Oasis
        ///Seagren Fine COMPANYs
        ///Tagus Residences
        ///Double Bay Residences
        ///Blue Harbour Senior Living
        ///Seaholm Residences
        ///Largos Residences
        ///Boathous Residences
        ///Centrepoint COMPANYs
        ///Brick Walls
        ///Pearls Hills
        ///Madison Residences
        ///H20 Residences
        ///Inspirit COMPANYs
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nameResidential {
            get {
                return ResourceManager.GetString("nameResidential", resourceCulture);
            }
        }
    }
}
