//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedBuildings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedBuildings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY was founded in DATE with the vision to apply creative thinking and state-of-the-art technology to traditionally low-tech industries, bolstered by a corporate culture renowned for putting customer service first. Based in Chattanooga, Tennessee, the COMPANY family of companies has become a global leader in the manufacture of equipment for asphalt road building, aggregate processing, oil, gas and water well drilling and wood processing, among others.
        ///COMPANY is a global management consulting firm that [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionsWorkplaces {
            get {
                return ResourceManager.GetString("descriptionsWorkplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceritfied Earth Movers Inc.
        ///Barkley&apos;s Gold Digger Industries
        ///Ballarat Bedrock Mines Corproration 
        ///The Boulder Quarry Syndicate
        ///Family Gravel Business Enterprise
        ///Doug&apos;s Titanium Miner Union
        ///Grandma&apos;s Aluminium Deposit Association
        ///Eureka Silver Reserves Multinational
        ///Klondike&apos;s Copper Trade Company
        ///Plinkett&apos;s Chromium Collector Organisation
        ///Walter&apos;s Platinum Merchant Congolomorate
        ///Californian Uranium Holdings League
        ///Crystal&apos;s Iron Fist Alliance
        ///Heavy Metal Industries
        ///Blue Steel Mill
        ///Rock and Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nameWorkplaces {
            get {
                return ResourceManager.GetString("nameWorkplaces", resourceCulture);
            }
        }
    }
}
